### ISSUE TITLE
Windows 中回显失败

### ISSUE THREAD

**Issue by zhzyker** [j1anFen/ysoserial_echo#1]
我在samples-web-1.2.4 windows环境中测试无法回显

我尝试使用：
```
java -jar yso-echo-SNAPSHOT-all.jar shiro win kPH+bIxk5D2deZiIxcaaaA==
```
和
```
java -jar yso-echo-SNAPSHOT-all.jar shiro windows kPH+bIxk5D2deZiIxcaaaA==
```
设定的命令并没有被执行，不过linux中均正常且能回显

**Comment by j1anFen** [comment]
项目里的payload shiro目前只支持spring环境下回显,复现的话可以试试这个环境：https://github.com/wuyouzhuguli/SpringAll/tree/master/12.Spring-Boot-Shiro-RememberMe
请问一下你的linux环境是基于spring的吗
